### PR TITLE
Add support for AddThis social share buttons

### PR DESCRIPTION
**Pull request by igordavydsson**
Add support for including AddThis social share buttons in necessary
templates. Bump plugin's version to 0.2.4.

Refs RND-10

### CODE REVIEW

**Review by JsseL — APPROVED** [review]
I think this is a welcome addition to the package. :+1:

**Comment by JsseL** [comment]
+1 for the docs by the way.

**Comment by JsseL** [comment]
Seems like you still need to fix the build..

**Comment by igordavydsson** [comment]
@JsseL yeah, rookie mistake: forgot `__init__.py` in `templatetags`. :)

**Comment by JsseL** [comment]
No points for maintaining test coverage. :zero: :smiley:

**Pull request merged**
